x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 1m
    max-file: 1

services:
  nginx:
    image: nginx:1.25.2
    environment:
      TOGOVAR_REFERENCE: ${TOGOVAR_REFERENCE:?}
    command:
      - /bin/sh
      - -c
      - "envsubst '$$TOGOVAR_REFERENCE' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app
      - jbrowse
      - sparqlist
      - sparql-proxy
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./docker/nginx/cache.sh:/usr/local/bin/cache:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/staging.conf:/etc/nginx/conf.d/default.conf.template:ro
      - ${PUBLIC_DIR:?}:/var/www/public:ro
      - app_sockets:/tmp/sockets:ro
      - nginx_www:/var/www
    logging: *default-logging

  app:
    image: ruby:3.2.4
    environment:
      RAILS_ENV: production
      WEB_CONCURRENCY: 10
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?}
      TOGOVAR_ELASTICSEARCH_HOST: elasticsearch01:9200
      TOGOVAR_REFERENCE: ${TOGOVAR_REFERENCE:?}
      TOGOVAR_FRONTEND_API_URL: ${TOGOVAR_FRONTEND_API_URL:-https://stg-togovar.org}
      TOGOVAR_ENDPOINT_SPARQL: ${TOGOVAR_ENDPOINT_SPARQL:-https://stg-togovar.org/sparql}
      TOGOVAR_REDIS_HOST: redis
      TOGOVAR_REDIS_PORT: 6379
      TOGOVAR_REDIS_SESSION_EXPIRE: ${TOGOVAR_REDIS_SESSION_EXPIRE:-86400}
      TOGOVAR_KEYCLOAK_URL: ${TOGOVAR_KEYCLOAK_URL:-}
      TOGOVAR_KEYCLOAK_CLIENT_SECRET: ${TOGOVAR_KEYCLOAK_CLIENT_SECRET:-}
      TOGOVAR_KEYCLOAK_BASE_URL: ${TOGOVAR_KEYCLOAK_BASE_URL:-}
      TOGOVAR_KEYCLOAK_REALM: ${TOGOVAR_KEYCLOAK_REALM:-}
      TOGOVAR_KEYCLOAK_CLIENT_ID: ${TOGOVAR_KEYCLOAK_CLIENT_ID:-}
      TOGOVAR_KEYCLOAK_AUTHORIZE_SCOPE: ${TOGOVAR_KEYCLOAK_AUTHORIZE_SCOPE:-}
      TOGOVAR_KEYCLOAK_AUTH_ATTRIBUTE_NAME: ${TOGOVAR_KEYCLOAK_AUTH_ATTRIBUTE_NAME:-}
      TOGOVAR_KEYCLOAK_AUTH_ATTRIBUTE_REGEX: ${TOGOVAR_KEYCLOAK_AUTH_ATTRIBUTE_REGEX:-}
    entrypoint: /docker-entrypoint.sh
    command:
      - start
    working_dir: /app
    volumes:
      - ./docker/ruby/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./backend:/app
      - app_bundle:/usr/local/bundle
      - app_sockets:/app/tmp/sockets
    logging: *default-logging

  jbrowse:
    build: docker/jbrowse
    image: togovar_jbrowse:2022.2
    volumes:
      - ./docker/jbrowse/template/jbrowse_conf.json:/var/www/jbrowse_conf.json:ro
      - ${JBROWSE_DATA:?}:/var/www/data
    logging: *default-logging

  sparqlist:
    image: ghcr.io/dbcls/sparqlist:snapshot-f444cf1
    environment:
      ADMIN_PASSWORD: ${SPARQLIST_ADMIN_PASSWORD:?}
      SPARQLIST_TOGOVAR_URL: ${TOGOVAR_FRONTEND_API_URL:-https://stg-togovar.org}
      SPARQLIST_TOGOVAR_APP: http://nginx
      SPARQLIST_TOGOVAR_SPARQL: http://sparql-proxy:3000/proxy/sparql
      SPARQLIST_TOGOVAR_SPARQLIST: http://sparqlist:3000/sparqlist
    volumes:
      - ./sparqlist:/app/repository
    logging: *default-logging

  sparql-proxy:
    build: docker/proxy
    image: togovar_proxy:2023.1
    environment:
      SPARQL_BACKEND: http://virtuoso:8890/sparql
      ADMIN_USER: admin
      ADMIN_PASSWORD: ${SPARQL_PROXY_ADMIN_PASSWORD:?}
      CACHE_STORE: redis
      REDIS_URL: redis://redis:6379
      MAX_CONCURRENCY: 50
      PASSTHROUGH: "true"
    depends_on:
      - virtuoso
      - redis
    logging: *default-logging

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.12
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: "false"
      DEFAULT_GRAPH: http://togovar.org
      VIRT_SPARQL_MaxQueryCostEstimationTime: 0
      VIRT_SPARQL_MaxQueryExecutionTime: 600
      VIRT_SPARQL_ResultSetMaxRows: 1000000
      VIRT_URIQA_DefaultHost: togovar.org
      VIRT_Parameters_NumberOfBuffers: 1360000
      VIRT_Parameters_MaxDirtyBuffers: 1000000
    volumes:
      - ${VIRTUOSO_DATA:?}:/database
    logging: *default-logging

  redis:
    image: redis:7.2.1
    logging: *default-logging

  elasticsearch01: &es
    image: elasticsearch:8.13.4
    ulimits:
      #memlock: # failed to set ulimits on rootless
      #  soft: -1
      #  hard: -1
      nofile:
        soft: 65535
        hard: 65535
    environment: &es_env
      ES_JAVA_OPTS: ${ELASTICSEARCH_JAVA_OPTS:--Xms16g -Xmx16g}
      TAKE_FILE_OWNERSHIP: "true"
      node.name: node01
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
      discovery.seed_hosts: elasticsearch02,elasticsearch03,elasticsearch04,elasticsearch05
      bootstrap.memory_lock: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enabled: "false"
      path.repo: /usr/share/elasticsearch/snapshot
    depends_on:
      - elasticsearch02
      - elasticsearch03
      - elasticsearch04
      - elasticsearch05
    volumes:
      - ${ELASTICSEARCH_01_DATA:?}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_SNAPSHOT:?}:/usr/share/elasticsearch/snapshot
    logging: *default-logging
    ports:
      - ${ELASTICSEARCH_PORT:-9200}:9200

  elasticsearch02:
    <<: *es
    environment:
      <<: *es_env
      node.name: node02
      discovery.seed_hosts: elasticsearch01,elasticsearch03,elasticsearch04,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_02_DATA:?}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_SNAPSHOT:?}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch03:
    <<: *es
    environment:
      <<: *es_env
      node.name: node03
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch04,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_03_DATA:?}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_SNAPSHOT:?}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch04:
    <<: *es
    environment:
      <<: *es_env
      node.name: node04
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch05
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_04_DATA:?}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_SNAPSHOT:?}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

  elasticsearch05:
    <<: *es
    environment:
      <<: *es_env
      node.name: node05
      discovery.seed_hosts: elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch04
      cluster.initial_master_nodes: node01,node02,node03,node04,node05
    volumes:
      - ${ELASTICSEARCH_05_DATA:?}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_SNAPSHOT:?}:/usr/share/elasticsearch/snapshot
    depends_on: []
    ports: []

volumes:
  app_bundle:
  app_sockets:
  nginx_www:
